# Generated by Django 2.0 on 2019-05-22 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orm.AddressInfo', verbose_name='自关联')),
            ],
        ),
        migrations.CreateModel(
            name='Aritcle',
            fields=[
                ('aritcle_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('brief_content', models.TextField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orm.A')),
            ],
        ),
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manytomany', models.ManyToManyField(to='orm.B')),
            ],
        ),
        migrations.AddField(
            model_name='a',
            name='onetoone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.Aritcle'),
        ),
    ]
