# Generated by Django 2.0 on 2019-05-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aritcle',
            name='brief_content',
            field=models.TextField(default='这位同学很懒哦'),
        ),
    ]
